version: '3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ${PWD}/conf:/etc/openvpn
    restart: unless-stopped
    ports:
      - 1194:1194/udp
    networks:
      - _net

networks:
  _net:
